#pragma once

#include "SP_PlanError.generated.h"

/** Error list generated by SPlanner. */
UENUM(BlueprintType, Category = "SPlanner|Planner")
enum class ESP_PlanError : uint8
{
	/** Unknown error. */
	PE_Unknown								UMETA(DisplayName = "Unknown"),

	/** ConstructPlan() failed. */
	PE_BadArgument							UMETA(DisplayName = "BadArgument"),

	/** ConstructPlan() failed. */
	PE_ConstructionFailed					UMETA(DisplayName = "ConstructionFailed"),

	/** LOD get out of range. */
	PE_LODOutOfRange						UMETA(DisplayName = "LODOutOfRange"),
};