#pragma once

#include "SP_PlanError.generated.h"

/** Error list generated by SPlanner. */
UENUM(BlueprintType, Category = "SPlanner|Misc")
enum class ESP_PlanError : uint8
{
	/** Unknown error. */
	PE_Unknown								UMETA(Display = "Unknown"),

	/** ConstructPlan() failed. */
	PE_ConstructionBadArgument				UMETA(Display = "ConstructionBadArgument"),

	/** ConstructPlan() failed. */
	PE_ConstructionFailed					UMETA(Display = "ConstructionFailed"),

	/** LOD get out of range. */
	PE_LODOutOfRange						UMETA(Display = "LODOutOfRange"),
};